grpc cart api
es-hs/erpc pull request #9
Opened 2022-01-19 10:26 UTC by TungSC

2022-01-25 03:13 UTC, vincentluan requested changes

2022-01-25 03:13 UTC, vincentluan commented on online_store/cart.proto
> +message Reply {
Em xem lại cách đặt tên nhé, đặt kiểu quá chung chung như này về sau rất dễ lẫn.

2022-01-25 03:13 UTC, vincentluan commented on online_store/cart.proto
> +    repeated CartLineUpdateInput cartLinesUpdateInput = 3;
File proto đều đang sử dụng camel case, sao file này em lại dùng snake case? Em cần để ý quan sát hơn nhé.

2022-01-25 04:18 UTC, vincentluan requested changes

2022-01-25 04:18 UTC, vincentluan commented on online_store/cart.proto
> +    repeated CartLineUpdateInput cartLinesUpdateInput = 3;
Em không hiểu ý anh rồi, chuyển hết sang snake case cho nó đồng nhất cả project đi em :))

2022-01-25 04:19 UTC, TungSC commented on online_store/cart.proto
> +    repeated CartLineUpdateInput cartLinesUpdateInput = 3;
@vincentluan vâng anh 😂

2022-01-25 12:20 UTC, vincentluan requested changes

2022-01-25 12:20 UTC, vincentluan commented on online_store/cart.proto
> +message CartResponse {
Để cái này là `Cart` đi em, vừa có `CartReply` lại có `CartResponse`, khác gì đánh đố mọi ng đâu em :))

2022-01-25 12:20 UTC, vincentluan commented on online_store/cart.proto
> +    //repeated DiscountAllocation shippingDiscountAllocations = 15;
Cái gì đã muốn bỏ thì bỏ luôn, cứ comment lại như này là ko bao giờ bỏ đâu em.

2022-01-26 04:09 UTC, vincentluan approved these changes

2022-01-26 04:09 UTC, merged